name: data_pipeline_workflow

on:
  workflow_dispatch:

  schedule:
    - cron: "30 2 * * *"

jobs:
  run-data-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: install dependencies
        run: pip install -r requirements.txt
        
      - name: run etl data pipeline
        run: python etl.py

      - name: check changes
        run: |  
          git config --global user.name 'Jean-LoupVacher2028486'
          git config --global user.email 'jean-loup.vacher@users.noreply.github.com'
          git add mydb.db
          git commit -am "Automated report"
          git push
